name: NodeJS CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Unit checks
        run: |
          npm ci
          npm test -- --reporters=jest-junit 
      - name: E2E checks
        run: |
          npm start &
          sleep 10
          npx wdio run ./wdio.conf.js
      - name: Build production artifacts
        run: |
          npm run build --if-present
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
           junit.xml
           reports/e2e-report/*.xml
      - name: Slack Notification Demo
        uses: actions/checkout@master
      - name: Slack Notification Demo
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
          SLACK_MESSAGE: 'Actions and Testing Message'
          SLACK_TITLE: 'Actions and Testing'           